version: "3.9"

services:
  fishbowl:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: docker
      DB_PASSWORD: 090513
      DB_NAME: fishbowl
    volumes:
      - ./public/uploads:/app/public/uploads  # 持久化上传的文件
