version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fishbowl
      MYSQL_USER: docker
      MYSQL_PASSWORD: 090513
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  fishbowl:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: docker
      DB_PASSWORD: 090513
      DB_NAME: fishbowl
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  mysql_data:
