'use client';

// Transitional aliases keep the existing call sites readable while the project
// uses one tree-shakeable icon library only.
export {
  Heart as LikeOutlined,
  Share2 as ShareAltOutlined,
  Camera as CameraOutlined,
  Save as SaveOutlined,
  Zap as ThunderboltOutlined,
  Plus as PlusOutlined,
  FileText as FileTextOutlined,
  Image as PictureOutlined,
  Code2 as CodeOutlined,
  Link as LinkOutlined,
  Trash2 as DeleteOutlined,
  Menu as MenuOutlined,
  ArrowUp as ArrowUpOutlined,
  ArrowDown as ArrowDownOutlined,
  Eye as EyeOutlined,
  CircleAlert as ExclamationCircleOutlined,
  Copy as CopyOutlined,
  Wrench as ToolOutlined,
  Paintbrush as FormatPainterOutlined,
  Minimize2 as CompressOutlined,
  Eraser as ClearOutlined,
  AlignLeft as AlignLeftOutlined,
  Undo2 as UndoOutlined,
  Search as SearchOutlined,
  Lock as LockOutlined,
  Clock3 as ClockCircleOutlined,
  Pencil as EditOutlined,
  User as UserOutlined,
  BookOpen as ReadOutlined,
  Rows3 as InsertRowAboveOutlined,
  ChartArea as AreaChartOutlined,
  CirclePlay as PlayCircleOutlined,
  Mail as MailOutlined,
  Home as HomeOutlined,
  Book as BookOutlined,
  LogIn as LoginOutlined,
  LogOut as LogoutOutlined,
  LayoutDashboard as DashboardOutlined,
  ClipboardPen as FormOutlined,
  Crown as CrownOutlined,
  List as UnorderedListOutlined,
  FishSymbol as IoFishOutline,
} from 'lucide-react';
