import { writeFileSync } from 'fs';
import { stringify } from 'yaml';
import { buildGptOpenapi } from '../lib/gptOpenapi';
for (const bundle of [undefined, 'curate', 'publish', 'illustrate']) {
  const content = '# Generated by npm run gpt:schema. Edit lib/gptOpenapi.ts.\n' + stringify(buildGptOpenapi(undefined, bundle));
  writeFileSync(`docs/gpt/${bundle ? `${bundle}-tool` : 'openapi'}.yaml`, content);
  if (!bundle) writeFileSync('public/gpt-openapi.yaml', content);
}
